import { parseAbi } from 'viem';
import { arbitrumSepolia } from 'viem/chains';

// --- Deployed Contract Addresses (Arbitrum Sepolia) ---
export const FUNDME_TOKEN_ADDRESS = '0x50B1727faC42e8a1223d8BAD850c884Cbabe477e' as const;
export const FUNDME_PLATFORM_ADDRESS = '0xDfD8E4d158c8dFA2043e23f6630907a30b79fD82' as const;
export const USDC_ADDRESS = '0x75faf114eafb1BDbe2F0316DF893fd58CE46AA4d' as const;

// The ERC-7984 wrapper mirrors the underlying testnet USDC, which is 6-decimal.
export const USDC_DECIMALS = 6;

// Canonical chain for every read/write. Every wagmi hook in this app must pin
// to this chainId so we never accidentally talk to the wallet's active chain.
export const CHAIN_ID = arbitrumSepolia.id;
export const BLOCK_EXPLORER_URL = 'https://sepolia.arbiscan.io';

// Primary IPFS gateway — Pinata's gateway is most reliable for content pinned there.
// Fallbacks are tried in order if the primary returns a non-200 status.
export const IPFS_GATEWAY = 'https://gateway.pinata.cloud/ipfs/';
export const IPFS_GATEWAY_FALLBACKS = [
  'https://cloudflare-ipfs.com/ipfs/',
  'https://ipfs.io/ipfs/',
];

// --- ABIs ---

// ERC-7984 wrapper (FundMeToken). Exposes the confidential wrap/unwrap pair
// plus the operator-authorization primitives used when sponsoring.
export const WRAPPER_ABI = parseAbi([
  'function wrap(address to, uint256 amount) public returns (bytes32)',
  // encryptedAmount is bytes32 (euint256 handle), NOT uint256
  'function unwrap(address from, address to, bytes32 encryptedAmount, bytes inputProof) public returns (bytes32)',
  'function finalizeUnwrap(bytes32 unwrapRequestId, bytes decryptedAmountAndProof) external',
  // ERC-7984 uses confidentialBalanceOf (returns encrypted handle as bytes32), not balanceOf
  'function confidentialBalanceOf(address account) view returns (bytes32)',
  'function isOperator(address holder, address operator) view returns (bool)',
  'function setOperator(address operator, uint48 until) public',
  'event UnwrapRequested(address indexed receiver, bytes32 amount)',
]);

// Plain ERC-20 used for the underlying USDC approvals + public balance read.
export const ERC20_ABI = parseAbi([
  'function approve(address spender, uint256 amount) public returns (bool)',
  'function balanceOf(address account) view returns (uint256)',
]);

// FundMePlatform main contract. Note: the autogenerated `projects(id)` getter
// does NOT return the nested `leaderboardIPFSHashes` string[]; use
// `getLeaderboardHistory(projectId)` for that.
export const PLATFORM_ABI = parseAbi([
  'function nextProjectId() view returns (uint256)',
  'function projects(uint256) view returns (address sponsoree, uint256 deadline, uint8 topKLimit, string reclaimProofId, bool isFinalized, uint256 lastRevealTimestamp, string title, string description, bool isAuction, uint256 minBidAmount, uint256 leaderboardCooldown)',
  'function getLeaderboardHistory(uint256 projectId) view returns (string[])',
  'function createProject(uint256 durationMinutes, uint8 topKLimit, string reclaimProofId, string title, string description, bool isAuction, uint256 minBidAmount, uint256 cooldownSeconds) external returns (uint256)',
  'function sponsorProject(uint256 projectId, bytes32 encryptedAmount, bytes inputProof) external',
  'function requestLeaderboardRefresh(uint256 projectId, bool isFinalReveal) external payable',
  'function withdrawProjectFunds(uint256 projectId) external',
  'function claimRefund(uint256 projectId) external',
  'function claimAuctionRefund(uint256 projectId) external',
  'function isTopKSponsor(uint256 projectId, address sponsor) view returns (bool)',
  'function topKSponsorsSet(uint256 projectId) view returns (bool)',
  'function projectWithdrawn(uint256 projectId) view returns (bool)',
  'function getAuctionWinner(uint256 projectId) view returns (address)',
  'function hasClaimedRefund(uint256 projectId, address sponsor) view returns (bool)',
  'function hasClaimedAuctionRefund(uint256 projectId, address sponsor) view returns (bool)',
  'function getContributionHandle(uint256 projectId, address sponsor) view returns (bytes32)',
  'event ProjectCreated(uint256 indexed projectId, address indexed sponsoree, uint256 deadline)',
  'event SponsorshipAdded(uint256 indexed projectId, address indexed sponsor, uint256 timestamp)',
  'event AuctionWinnerSet(uint256 indexed projectId, address indexed winner)',
  'event TopKSponsorsSet(uint256 indexed projectId, address[] winners)',
  'event AuctionRefundClaimed(uint256 indexed projectId, address indexed sponsor)',
  'event RefundClaimed(uint256 indexed projectId, address indexed sponsor)',
]);

// Gas limit for sponsorProject. The function executes 5 Nox FHE operations
// (fromExternal, allowTransient, confidentialTransferFrom, add, allow) which
// genuinely cost 2–5 M gas on Arbitrum Sepolia.  We pin an upper bound here so
// that MetaMask never falls back to the block gas limit (~32 M) when
// eth_estimateGas fails because the input-proof is tied to the latest block
// but estimation runs against the pending block.
export const SPONSOR_GAS_LIMIT = 4_000_000n;

// Returns EIP-1559 fee params so writeContractAsync uses type-2 transactions on
// Arbitrum Sepolia — you pay baseFee + a small priority fee rather than the full
// legacy gasPrice ceiling. Falls back to legacy gasPrice if estimateFeesPerGas
// is unavailable.
// Usage: spread the result into writeContractAsync({ ..., ...await getGasOverride(publicClient) })
export async function getGasOverride(
  publicClient: { getGasPrice(): Promise<bigint>; estimateFeesPerGas?(): Promise<{ maxFeePerGas: bigint; maxPriorityFeePerGas: bigint }> },
): Promise<{ maxFeePerGas: bigint; maxPriorityFeePerGas: bigint } | { gasPrice: bigint }> {
  try {
    const fees = await (publicClient as any).estimateFeesPerGas?.();
    if (fees?.maxFeePerGas != null) {
      return {
        // 10 % buffer on the base-fee cap to survive a block or two of fee bumps
        maxFeePerGas: (fees.maxFeePerGas * 110n) / 100n,
        // keep priority fee small — 1 gwei is enough on Arbitrum Sepolia
        maxPriorityFeePerGas: fees.maxPriorityFeePerGas,
      };
    }
  } catch {
    // fall through to legacy path
  }
  const gasPrice = await publicClient.getGasPrice();
  return { gasPrice: (gasPrice * 110n) / 100n };
}

// Strongly-typed shape we decode `projects(id)` into in React components.
export type ProjectRecord = {
  sponsoree: `0x${string}`;
  deadline: bigint;
  topKLimit: number;
  reclaimProofId: string;
  isFinalized: boolean;
  lastRevealTimestamp: bigint;
  title: string;
  description: string;
  isAuction: boolean;
  minBidAmount: bigint;
  leaderboardCooldown: bigint;
};

// Shape expected in an IPFS-hosted leaderboard JSON.
export type LeaderboardEntry = {
  rank: number;
  sponsor: `0x${string}`;
  amount?: string;
};

export type LeaderboardPayload = {
  projectId: number;
  generatedAt: number;
  isFinal?: boolean;
  isAuction?: boolean;
  winnerAddress?: string;
  minBidAmount?: number;
  totalFunded?: number;
  highestBid?: number;
  entries: LeaderboardEntry[];
};
